### ISSUE TITLE
Doesn't work with 4-bit codes

### ISSUE THREAD

**Issue by zanhecht** [jpliew/Wiegand-NG-Multi-Bit-Wiegand-Library-for-Arduino#1]
I have a weigand reader and have it hooked up and working on my arduino using the old weigand.h library. However, when I use this library I can scan cards of 26 or 32 bits it works fine, but when I try to use the pin pad, which returns 4-bit number, I get an output that just says:
>Bits=4
>RAW Binary=

In other words, it's returning the number of bits, but not the bits themselves.

**Comment by jpliew** [comment]
I think there is a bug at line 10-12 in WiegandRawTest.ino 

countedBits / 8 in your case 4 bits 4/8 to unsigned int is 0 which is not correct.

```
unsigned int countedBytes = (countedBits/8);
if ((countedBytes % 8)>0) countedBytes++;
unsigned int bitsUsed = countedBytes * 8;
```

**Comment by zanhecht** [comment]
That makes sense. Looks like changing (countedBytes % 8) to (countedBits % 8) fixes it.

**Comment by jpliew** [comment]
Fixed by @zanhecht
